### ISSUE TITLE
Collection was modified error in Jaeger.Reporters.RemoteReporter

### ISSUE THREAD

**Issue by xumix** [jaegertracing/jaeger-client-csharp#132] opened 2019-03-20 16:05 UTC
Getting this error in async http handler setup. Looks like you should `.ToArray()` all enumerable things before `foreach` or use some locking primitives when reporting.

```
Jaeger.Reporters.RemoteReporter:Error: QueueProcessor error

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Jaeger.Reporters.Protocols.JaegerThriftSpanConverter.BuildLogs(IEnumerable`1 logs) in C:\projects\jaeger-client-csharp\src\Jaeger\Reporters\Protocols\JaegerThriftSpanConverter.cs:line 69
   at Jaeger.Reporters.Protocols.JaegerThriftSpanConverter.ConvertSpan(Span span) in C:\projects\jaeger-client-csharp\src\Jaeger\Reporters\Protocols\JaegerThriftSpanConverter.cs:line 26
   at Jaeger.Senders.ThriftSender.AppendAsync(Span span, CancellationToken cancellationToken) in C:\projects\jaeger-client-csharp\src\Jaeger\Senders\ThriftSender.cs:line 40
   at Jaeger.Reporters.RemoteReporter.ProcessQueueLoop() in C:\projects\jaeger-client-csharp\src\Jaeger\Reporters\RemoteReporter.cs:line 133
OpenTracing.Contrib.NetCore.CoreFx.GenericDiagnostics:Trace: No ActiveSpan. Event: SqlClientDiagnosticListener/System.Data.SqlClient.WriteConnectionOpenBefore
Microsoft.AspNetCore.Server.Kestrel:Debug: Connection id "0HLLD9EFNDACG" completed keep alive response.
OpenTracing.Contrib.NetCore.CoreFx.GenericDiagnostics:Trace: No ActiveSpan. Event: SqlClientDiagnosticListener/System.Data.SqlClient.WriteConnectionOpenAfter
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 64379.5532ms 500 
OpenTracing.Contrib.NetCore.CoreFx.GenericDiagnostics:Trace: No ActiveSpan. Event: SqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandBefore
Jaeger.Reporters.LoggingReporter:Information: Span reported: cecb616108672f42:cecb616108672f42:0:1 - HTTP GET
OpenTracing.Contrib.NetCore.CoreFx.GenericDiagnostics:Trace: No ActiveSpan. Event: SqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandAfter
OpenTracing.Contrib.NetCore.CoreFx.GenericDiagnostics:Trace: No ActiveSpan. Event: SqlClientDiagnosticListener/System.Data.SqlClient.WriteConnectionCloseBefore
OpenTracing.Contrib.NetCore.CoreFx.GenericDiagnostics:Trace: No ActiveSpan. Event: SqlClientDiagnosticListener/System.Data.SqlClient.WriteConnectionCloseAfter
```

Unfortunately I couldn't reproduce the problem in an isolated env and my project is rather large to post it here :(

**Comment by Falco20019** [comment] 2019-03-20 16:10
This is a duplicate of #129 and will be fixed in v0.3.0 which should be released soon. Only waiting for #128 to be reviewed.

**Closed by Falco20019** 2019-03-20 16:10 UTC

**Comment by xumix** [comment] 2019-03-20 16:17
Ok thanks!

**Comment by Falco20019** [comment] 2019-03-22 14:44
@xumix Version 0.3.0 was just released and should be available through NuGET in the next hour.

**Comment by xumix** [comment] 2019-03-22 16:15
@Falco20019 thanks a lot!
