### ISSUE TITLE
Read configuration over appsettings.json

### ISSUE THREAD

**Issue by N3IS** [jaegertracing/jaeger-client-csharp#133] opened 2019-03-22 15:49 UTC
## Requirement - what kind of business use case are you trying to solve?

I would like to create a tracer with my configurations set in the appsettings.json instead of the environment variables.

## Problem - what in Jaeger blocks you from solving the requirement?

The Jaeger.Configuration.cs

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I solved the problem for myself by writing my necessary environment variables in the appsettings.json in a new Jaeger section and copied the Jaeger.Configuration.cs in a new class library. My new Jaeger section in appsettings.json: 

```
  "Jaeger": {
    "JAEGER_SERVICE_NAME": "service",
    "JAEGER_AGENT_HOST": "localhost",
    "JAEGER_AGENT_PORT": "6831",
    "JAEGER_SAMPLER_TYPE": "const",
    "JAEGER_SAMPLER_PARAM": "1"
  },
```

To use this section I gave the "Configuration.FromEnv" method the Jaeger section as IConfigurationSection as a new parameter and wrote a new field "_configurationSection" which got the parameter as new value. After that I changed the "GetProperty" method to :

        private static string GetProperty(string name)
        {
            return _configurationSection[name];
        }

At the end I renamed all methods with "*FromEnv" to "*FromApp" and it works fine. But now I have to check by every update the new Configuration.cs and my own that they will still work. 

This are just a few small changes in the code to use the appsettings.json as configuration file. Wouldn't it be possible to implement this feature into the Configuration File or to create two separate files "CofigurationEnv.cs" and "ConfigurationApp.cs"?

**Comment by Falco20019** [comment] 2019-03-22 16:10
Duplicate of #110. Please use the following code:
```csharp
var configuration = new ConfigurationBuilder()
  .AddJsonFile("appsettings.json")
  .Build();
var tracer =  Configuration.FromIConfiguration(_loggingFactory, configuration).GetTracer();
```

**Comment by N3IS** [comment] 2019-04-01 08:25
Thanks for the fast answer but i have tested the new FromIConfiguration method, but it isn't really working because the FromIConfiguration calls all old FromEnv methods for the Reporter, Sampler and Codec. 

https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/Configuration.cs#L167

And the FromEnv methods like SamplerConfiguration.FromEnv are creating there own new configuration with the environments variables which are passed to the new SamplerConfiguration.FromIConfiguration method which is only used this way.

https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/Configuration.cs#L340

Did I miss something or is this a bug?

**Comment by Falco20019** [comment] 2019-04-01 13:22
That's a bug :) Thanks for recognizing. I will create a PR for it.

**Comment by Falco20019** [comment] 2019-04-01 13:41
It should arrive in v0.3.1 that I hope to release beginning of next week, depending on the progress of the PRs.

**Closed** 2019-04-03 11:58 UTC

**Comment by Falco20019** [comment] 2019-04-03 12:28
v0.3.1 has just been released and should be listed on NuGET in the next hour.
